### ISSUE TITLE
Dynamic Zoom not applied via OFX plugin (Resolve 17/Fusion)

### ISSUE THREAD

**Issue by jhancuff** [gyroflow/gyroflow-ofx#10]
As far as I can tell, every other aspect of GyroFlow works great in Resolve.  The only thing that doesn't appear to be applied is the dynamic zoom.  Otherwise, silky smooth and relatively quick!

**Comment by jhancuff** [comment]
![image](https://user-images.githubusercontent.com/59770696/155577791-c4c46d76-112d-408e-875f-5a220f1dbf2f.png)
Example:

**Comment by AdrianEddy** [comment]
Fixed in v1.0.3
