### ISSUE TITLE
Only distortion correction is applied after importing .gyroflow file

### ISSUE THREAD

**Issue by a-Gugs** [gyroflow/gyroflow-ofx#11]
After properly importing the .gyroflow file exported with motion data, no stabilization appears and only distortion correction is applied.

![image](https://user-images.githubusercontent.com/75222071/158044473-80d7f661-7daf-4685-9044-c6cf88ca715f.png)

**Comment by ghuser123321** [comment]
Assume this is because of the new Default v2.0 beta stabilization method no yet supported. Code seems behind. Chose the old Default and it works at least for me.

**Comment by a-Gugs** [comment]
Thanks for the answer. What gyroflow version should I use?

**Comment by ghuser123321** [comment]
Currently I'd say wait until the OFX updated. Even if stabilization works, it's pretty bad compared to standalone for me: https://github.com/gyroflow/gyroflow-ofx/issues/15

**Comment by AdrianEddy** [comment]
Fixed in v1.0.3
