### ISSUE TITLE
Changing clip speed in Resolve breaks stabilization

### ISSUE THREAD

**Issue by User-3090** [gyroflow/gyroflow-ofx#13]
Changing clip speed in Resolve to say 50% breaks stabilization. I suppose because it uses timestamps and not frame numbers in gyro data!?

**Comment by ghuser123321** [comment]
I'd suggest to provide a configuration field for the OFX to set the actual framerate the clip has in the OFX host (e.g. Resolve).

**Comment by AdrianEddy** [comment]
I wasn't able to find an OpenFX API to get anything useful for this, it only provides frame numbers, but of a timeline, so changing any speed of a clip in Resolve doesn't change the values passed to the plugin. So there's no way for plugin to know if anything was changed on the clip.

**Comment by AdrianEddy** [comment]
This should be fixed in v1.0.6.
Even though it should work (only for static speed change), it's better to now use Gyroflow's built-in video speed slider with optional keyframes than changing clip speed in Resolve
