### ISSUE TITLE
Documentation says use Fusion, but it works so much better on Resolve color page

### ISSUE THREAD

**Issue by User-3090** [gyroflow/gyroflow-ofx#14]
Gyroflow OFX works 3-4 times faster on the Resolve color page than in Resolve Fusion. For me real time 1080 60p. I can't see a point of dealing with all the slowness and overhead of Fusion in Resolve when it works so much better in the Color Page.

I'd vote to change the documentation so new users get a better experience.

**Comment by paytonfrost** [comment]
Came here to second this. With the recent update to the plugin 1.0.2-beta.1 I wasn't able to get it to work in the Fusion page, but stumbling across this comment made me try it in the Color page and it worked! Played back mostly smooth (But I was also working with a raw dng file).

**Comment by AdrianEddy** [comment]
Thanks, updated README to mention that

**Comment by TalkinBull** [comment]
Hi Adrain, I just tested this in Davinci.  The plug-in is working as expected in Fusion, however it only applies the lens correction when added via the Color page.

**Comment by AdrianEddy** [comment]
Hmm, it works correctly for me both in Fusion and Color page on Windows. What system are you using? Can you upload the video file and .gyroflow file?

**Comment by TalkinBull** [comment]
> Hmm, it works correctly for me both in Fusion and Color page on Windows. What system are you using? Can you upload the video file and .gyroflow file? Also did you use latest v1.0.3 version?

Yes, I was using the  v1.0.3 version of the plug-in.  I've sent you the Proxy Media, Davinci Project and Gyroflow file via WeTransfer.   I also sent the GoPro file that I used for the Gyro data.  I'm working on the BRAW file.  It's 5GB.
Cheers

**Comment by AdrianEddy** [comment]
@TalkinBull please try v1.0.4 in the color page, should be fixed
