### ISSUE TITLE
Stablilization not as good as stand alone version. Suspect micro timing issues.

### ISSUE THREAD

**Issue by User-3090** [gyroflow/gyroflow-ofx#15]
With GoPro Hero 10 footage I find the stabilization much worse than with the stand alone version. I notice that Gyroflow stand alone and Resolve reports slightly different clip length and I suspect that Gyro data is slightly out of sync with frames.

This is also what it looks like. Large movements are compensated for, but all the micro jitter / wobble not at all or even amplified.

This is exactly the scenario I would anticipate when importing VFR footage into Resolve as Resolve will clamp frames one by one to timeline frames making the clip CFR and then timestamp based Gyro data would be out of sync.

But this happens with CFR footage from a Here 10 and it happens all the time. Something is wrong.

FWIW I tested all of this with 4k 120p records. Can supply sample footage if needed.

**Comment by ghuser123321** [comment]
I thing some logic to convert from gyro timestamps to actual frame numbers would solve this and other issues. Then frame rate of the clip inside the OFX host would no longer matter and even speed ramping inside the OFX host would not break things.

**Comment by AdrianEddy** [comment]
Fixed in v1.0.3
