### ISSUE TITLE
Usage on Apple Silicon?

### ISSUE THREAD

**Issue by Manouchehri** [gyroflow/gyroflow-ofx#16]
Just wondering, have any of you had success using this with Apple Silicon chips? In [DaVinci Resolve 18](https://www.blackmagicdesign.com/products/davinciresolve/whatsnew), Gyroflow isn't showing up at all.

<img width="360" alt="image" src="https://user-images.githubusercontent.com/7232674/165601144-bc2f1d3a-7b33-4b77-8cb7-bd60b8348753.png">

**Comment by ilya-epifanov** [comment]
It's blocked by https://github.com/actions/virtual-environments/issues/2187

**Comment by AdrianEddy** [comment]
> It's blocked by [actions/virtual-environments#2187](https://github.com/actions/virtual-environments/issues/2187)

Hmm, x64 macs can cross-compile to arm64, this is how Gyroflow is built on Github Actions

**Comment by AdrianEddy** [comment]
Fixed in v1.0.3
