### ISSUE TITLE
Davinci Resolve crashing after adding Gyroflow stabilization

### ISSUE THREAD

**Issue by TalkinBull** [gyroflow/gyroflow-ofx#18]
I'm a using a Windows PC on Windows 11 with AMD Ryzen 9 5950X 16-Core Processor and 64.0 GB RAM.  Davinci Resolve 18.OB Build 32
The footage is shot with a BMPCC4K and the Gyro data captured on a Hero Session 5 and synced in Gyroflow.
I've created a project in Davinci Resolve and imported the footage into the timeline.  Under the Fusion tab I've added the Gyroflow node and browsed to the correct gyroflow project data file.
The first clip I tried worked correctly.  It ran for about 10 seconds.
The second clip I tried is just over a minute.  I followed the same steps.  When I add the gyroflow project data file into the Gyroflow node in the Fusion tab, Davinci Resolve shuts down after about 2 seconds.
I repeated the steps 3 times with the same result.  On the 4th attempt I saved the project.  Davinci Resovle shuts down when I try to open this project.

**Comment by AdrianEddy** [comment]
Can you upload the video file, .gyroflow file and the resolve project?

**Comment by AdrianEddy** [comment]
Please try v1.0.4 and let me know if it works https://github.com/gyroflow/gyroflow-ofx/releases
