### ISSUE TITLE
Plugin doesn't show in Magix Vegas

### ISSUE THREAD

**Issue by DavidHi75** [gyroflow/gyroflow-ofx#20]
Hello! I'm a Magix Vegas user, and I'm trying to use Gyroflow as a plugin under that host.
I've tried unzipping the archive both in "C:\Program Files\Common Files\OFX\Plugins" and in "C:\Program Files\VEGAS\VEGAS Pro 19.0\OFX Video Plug-Ins" but without any success.
I can't find the plugin anywhere in the software.
Is there any chance to use it in Vegas?

Thank you very much... David from Italy.

**Comment by xviews** [comment]
The same problem happens to me, I think it only works in DaVinci.

**Comment by DavidHi75** [comment]
Hello again!
Any hope to see this OFX plugin work under Magix Vegas???

Thank you very much.

**Comment by xviews** [comment]
cool thanks, I'll test it

**Comment by DavidHi75** [comment]
YOU ARE GREAT!!! I'm gonna test it as soon as possible!!!
