### ISSUE TITLE
Current build broken in Resolve Fusion?

### ISSUE THREAD

**Issue by User-3090** [gyroflow/gyroflow-ofx#21]
Works fine in Color, can't get it to produce anything in Fusion anymore.

Error: nl.smslv.gyroflowofx.fisheyestab_v1 returned <invalid status> from OfxImageEffectActionGetFramesNeeded
Error: nl.smslv.gyroflowofx.fisheyestab_v1 returned <invalid status> from OfxImageEffectActionRender
MediaOut1 cannot get Parameter for Input at time 794
MediaOut1 failed at time 794

**Comment by AdrianEddy** [comment]
Fixed in 6da02e175b8b0dfff9755e89fb4b68feb2f4595b version 1.0.11
