### ISSUE TITLE
Feature request — a button to start Gyroflow app

### ISSUE THREAD

**Issue by valenokk** [gyroflow/gyroflow-ofx#22]
It would be really nice to have a button, which will open a standalone Gyroflow app and let us edit settings. 
Editing a project with 320 stabilised files from GoPro, it's quite a tedious process right now.

**Comment by AdrianEddy** [comment]
Done:
https://nightly.link/gyroflow/gyroflow-ofx/workflows/build/main/gyroflow-ofx-windows.zip
https://nightly.link/gyroflow/gyroflow-ofx/workflows/build/main/gyroflow-ofx-linux.zip
https://nightly.link/gyroflow/gyroflow-ofx/workflows/build/main/gyroflow-ofx-macosx.zip
