### ISSUE TITLE
Doesn't work in Davinvi Resolve.

### ISSUE THREAD

**Issue by toferzim** [gyroflow/gyroflow-ofx#24]
Hello!
I've tried it in Davinci 17 and 18.1. Stabilization is not working while in the GyroFlow software it works fine. Seems like only a lens correction and rolling shutter works. But I'm not sure about a rolling shutter I can just see something happening with image deformation. 

I use it with CinemaDNG files from SIgma fp.

**Comment by AdrianEddy** [comment]
did you use latest version of the plugin? v1.0.11
did you add it to the fusion page or edit/color page?
what happens if you increase the FOV slider in the plugin?

**Comment by toferzim** [comment]
Hi! I used the latest version available. I've tried it in Color Tab and in Edit Tab. Nothing is changing when I use a smooth slider.(

**Comment by AdrianEddy** [comment]
Can you send me the video + project file?

**Comment by toferzim** [comment]
https://disk.yandex.ru/d/8YZ5I73zGVX6cQ

I had to compress it because cinemaDNG sequence is about 9Gb. I have no any options to upload it. But this h.264 file in the folder also doesn't work in Davinci. May be it is important but I have a M1 Pro Macbook Pro

**Comment by AdrianEddy** [comment]
It looks like your offsets are wrong and it doesn't play correctly in gyroflow either.
Try this project file, offsets are around -1020ms to -1090ms  
[testgyro.zip](https://github.com/gyroflow/gyroflow-ofx/files/10181135/testgyro.zip)

**Comment by toferzim** [comment]
Thank you! I will try tomorrow. But why can my GyroFlow export incorrect offsets?

**Comment by AdrianEddy** [comment]
It didn't export incorrect offsets, you must have had them wrong beforehand in gyroflow

**Comment by toferzim** [comment]
Not at all) at GyroFlow it looks smooth like a butter) I will send you tomorrow also a stabilized file. Seems like my GyroFlow does not export offsets..( how do you export data for OFX? Export a project with gyro processed data?

**Comment by AdrianEddy** [comment]
it exports offsets, you had -1800ms, the correct one for me was -1000ms, unless the video you sent has different frame rate or something changed during conversion. What's the gyro source? Are you sure your frame rates in gyroflow and in Resolve are identical?

**Comment by AdrianEddy** [comment]
I see the fps in your project file is 25fps, is that what you set in Resolve for the image sequence and timeline?

**Comment by toferzim** [comment]
Yes! Frame rates are identical. As far as I use cinemaDNG you have to set frame rate in GyroFlow manually and Davinci is set to 25fps as well. My Gyro data comes from a DIY gyrologger, but I've synced it manually precisely. My video stabilized in GyroFlow looks great and smooth. But when I export data and add the same data to Davinci, it doesn't work for some reason(

**Comment by toferzim** [comment]
That is for sure) it was my first thought when I got this problem)

**Comment by AdrianEddy** [comment]
then somehow your image sequence and the mp4 video you sent me is different, because the offsets needed to be different. Maybe you can convert the dngs to jpg (keep same resolution but you can set quality to something low to keep file size small) and share the jpg sequence?

**Comment by toferzim** [comment]
I will try tomorrow) and write you here

**Comment by toferzim** [comment]
Sorry, that was my mistake. I've rechecked it many times and tried another video. seems like there was something wrong with how I've synced that file and did some mistake. Seems like there was some syncing point somewhere out of my view that messed my offsets. Thank you for your assistance. SOLVED
