### ISSUE TITLE
Issues found while testing GoPro Footage

### ISSUE THREAD

**Issue by samuraitheta** [gyroflow/gyroflow-ofx#25]
Hello! Thank you for your excellent work on this project! 

I am planning on getting a BMPCC 6k to use with this setup, but I wanted to do some testing with a GoPro first. Here are a few issues I ran into:
If I try to add the Gyroflow OpenFX to a node in the Color section of Resolve... It doesn't give me a "Browse" button like it does in the Fusion section. I can paste the file location from the Fusion section into the Color section, but I'd love a "brose" button. Is this intentional, or would there be a way to add this?
Usually, I record in in 4/3 and crop to 16/9 in stabilization. (Obviously this won't be a problem with the BMPCC, but for the GoPro situation it would be nice to apply color before the crop) I can't seem to find a way to make the Plugin output 16/9. It just gives me the original 4/3 ratio and gives me black bars on the left and right of my 16/9 Timeline. 
Lastly, is there a way to include the ability to process upside-down camera? I recorded my files with the gopro mounted upside down. Currently, the Gyroflow OpenFX flips the camera upside down and the warping is backwards. If I transform the incoming video signal 180 then it works correctly. 

Thank you again for all of your hard work! I really appreciate it!

**Comment by AdrianEddy** [comment]
1. The lack of Browse button is a limitation of the OpenFX and Resolve - code requests the button but Resolve ignores it in the color tab. I can't do anything about it
2. To output 16:9 from 4:3 use "Project settings" -> "Image Scaling" -> "Mismatched resolution files" -> "Scale entire image to fit". Then create 16:9 timeline and drop the 4:3 file there. It should be fitted to the height with black bars on the sides. If you then apply Gyroflow plugin, it will use that 4:3 to make 16:9 and fill the entire timeline
3. I think you have to rotate it 180 like that, plugin doesn't have any info about the rotation metadata in file and how Resolve interprets it

**Comment by samuraitheta** [comment]
1. This is unfortunate, but it seems to work just pasting the file path into the box. 
2. This doesn't seem to work. It still outputs an image with black bars
3. I look forward to your rotation research! Thank you!

**Comment by samuraitheta** [comment]
https://user-images.githubusercontent.com/25701202/215367842-48433a59-0114-42db-9582-570a8e0c957c.mov

**Comment by AdrianEddy** [comment]
Try the latest dev build of the plugin, it solves all these issues:

https://nightly.link/gyroflow/gyroflow-ofx/workflows/build/main/gyroflow-ofx-windows.zip
https://nightly.link/gyroflow/gyroflow-ofx/workflows/build/main/gyroflow-ofx-linux.zip
https://nightly.link/gyroflow/gyroflow-ofx/workflows/build/main/gyroflow-ofx-macosx.zip

+use latest app
https://gyroflow.xyz/devbuild/?autodownload
