### ISSUE TITLE
Gyroflow plugin crop 4/3 to 16/9 not working in timeline

### ISSUE THREAD

**Issue by samuraitheta** [gyroflow/gyroflow-ofx#26]
I posted this as a reply to a previous post, but when I drop 4/3 clips into a 16/9 timeline and apply gyroflow... it applies black bars to the sides of the 16/9 stabilized video. 

https://user-images.githubusercontent.com/25701202/215378304-044fbbce-b264-4a8b-9b36-fa2b7f6c6fda.mov

**Comment by AdrianEddy** [comment]
You have to right click on the nodes -> "Add alpha output" and connect alpha output of the last node with the newly added alpha output point
![image](https://user-images.githubusercontent.com/3849067/215429763-687d12b8-72bc-420d-bc83-6ffbb5ecc56a.png)
![image](https://user-images.githubusercontent.com/3849067/215429836-e78d00eb-f9d5-46a8-b1a7-3eb102a569c0.png)
