### ISSUE TITLE
Caching of processed video clips 

### ISSUE THREAD

**Issue by muepla** [gyroflow/gyroflow-ofx#27]
@AdrianEddy 
About a week or so you added a cache to the DaVinci Gyroflow plugin for processed video clips.

  `static ref MANAGER_CACHE: Mutex<LruCache<String, Arc<StabilizationManager>>> `

The cache does work but if you add the same clip twice to the timeline or if you cut a clip, it creates some unwanted side effects:

As intended, the second clip inherits all stabilization parameters of the first clip but the UI is grayed out. After a restart of DaVinci, the UI is enabled but the sliders do not work/reflect the actual stabilization parameters. 

The workaround is probably a 'copy-on-write' caching algorithm.

**Comment by AdrianEddy** [comment]
Thanks, that's a good catch.

It has now been corrected: https://github.com/gyroflow/gyroflow-ofx/actions/runs/4286035444
BTW, new nightly app is available too https://gyroflow.xyz/devbuild/?autodownload
