### ISSUE TITLE
No stabilization if timeline has different framerate from the original video

### ISSUE THREAD

**Issue by stigla610** [gyroflow/gyroflow-ofx#30]
First I have to say, this is a fantastic update, thank you to everyone who is working on this project for all the hard work.

I have an issue when my timeline framerate (29.97 fps) doesn't match the original footage (59.94 fps). I get a message "Timeline fps mismatch!" This should make the plugin use every second frame but for some reason, the beginning of the video is stabilized but after a while it gets shaky.

**Comment by AdrianEddy** [comment]
That should be fixed in latest dev build https://github.com/gyroflow/gyroflow-ofx/actions/runs/5237037948
