### ISSUE TITLE
Results from the Davinci and the Gyroflow app are differrent

### ISSUE THREAD

**Issue by SpaceStar** [gyroflow/gyroflow-ofx#31]
After update I've got different results from the Davinci and Gyroflow using same project file. I've found that smoothness 1.7 in the plugin matches with 0.7 in the app to get the same results.

**Comment by AdrianEddy** [comment]
Indeed, very interesting find!
Fixed in https://github.com/gyroflow/gyroflow/commit/c7a22c423481c264c84c7ff782b6c9629343f3d5
available in latest dev build https://github.com/gyroflow/gyroflow-ofx/actions/runs/5095803018

**Comment by SpaceStar** [comment]
@AdrianEddy you fixed this issue in the core app but write a link to the plugin builds. Am I need to update the ofx plugin or the app or both for testing the fix?

**Comment by AdrianEddy** [comment]
updating just the plugin should be enough to fix this, but ideally you should update both, as there were some additional fixes in the app as well https://gyroflow.xyz/devbuild/?autodownload
