### ISSUE TITLE
Possible to expose stabilization data from Fusion node?

### ISSUE THREAD

**Issue by czukowski** [gyroflow/gyroflow-ofx#33]
Would it be possible to enable access to some stabilization data from Gyroflow node in Fusion?

At the moment, the only one of interest for me would be an angle from the Horizon lock but perhaps some other parameters would be of use to the others. My own use cases would include:

- Using a regular Transform node and using a Gyroflow node for its Angle input after some adjustments
- Creating some kind of a feedback loop, ie doing some calculations based on the input angle and dynamically adjusting Horizon lock level in the Gyroflow 

Thanks for consideration!

**Comment by AdrianEddy** [comment]
I'm not familiar with Resolve scripting, but all parameters in the plugin should be available for expressions and scripts already. Have you tried that?

**Comment by czukowski** [comment]
The parameters to control the amount of e.g. Horizon Lock are accessible to scripting, I was wondering if it was possible to expose the actual stabilization data, those represented by graphs in Gyroflow, as some sort of additional outputs that could be read by the scripts.

An example that would be of interest to me specifically, is to control the amount of Horizon Lock based on the actual camera angle (to allow a certain amount of horizon roll, but if it's higher than it, then increase Horizon Lock amount), using scripting.

Maybe it's already possible and I just can't see the correct parameter, I found one named `Rotation` but it always reads zero...

**Comment by AdrianEddy** [comment]
Closing in favor of https://github.com/gyroflow/gyroflow-plugins/issues/3 which is basically the same
