### ISSUE TITLE
Issue with video footage shake amplification

### ISSUE THREAD

**Issue by 01Kuzma** [gyroflow/gyroflow-ofx#37]
Hello!

I am writing to report an issue I have encountered while using the plugin in conjunction with my Sony a7IV camera and Davinci Resolve 18.1.4 software. The problem revolves around the plugin amplifying the shake present in my video footage, rather than smoothing it as intended.

Here are the specific details of my setup:

Camera: Sony a7IV
FPS: 25/50
Shutter Speed: 1/400

Software: Davinci Resolve 18.1.4

Plugin's settings are set to default.

**Comment by AdrianEddy** [comment]
Does it work in the Gyroflow app? Did you load the lens profile? 
Do you have all internal stabilization in camera disabled?

**Comment by 01Kuzma** [comment]
>Does it work in the Gyroflow app?

Well, no, only in Davinci

>Did you load the lens profile?

Would be grateful, if you tell where I could grab it for Sony lenses

>Do you have all internal stabilization in camera disabled?

No, I've used the active stabilization to test it together. Is it the wrong idea?

**Comment by AdrianEddy** [comment]
Currently Gyroflow doesn't support any in-camera stabilization, so OIS, IBIS and Active stabilization need to be turned off for Gyroflow to work
This may be supported in the future but it's not supported yet.

Loading a correct lens profile for your exact lens is also very important, a lot of lens profiles are included in the main Gyroflow app.

You can use Sony's Catalyst Browse for now, as it supports all internal stabilization modes

**Comment by 01Kuzma** [comment]
Understood,
thank you for clarification!
