### ISSUE TITLE
Gyroflow OFX failed to load on Davinci Resolve Linux

### ISSUE THREAD

**Issue by ducdigital** [gyroflow/gyroflow-ofx#45]
After trying to install Gyroflow OFX on Arch and on Fedora, I still not manage to load the plugin on Davinci Resolve 18.5 and 18.

![image](https://github.com/gyroflow/gyroflow-ofx/assets/1712140/42f2dd05-ea9b-4457-a9cf-27a469d8e279)

I also tried to run the Gyroflow OFX directly from command line but got a Segfault (probably not the way it intended to be used)

Are there anyway to debug the loading of this OFX? What are the lib requirement for this OFX to work? Right now I run gyroflow directly from the .tar.gz but is it require gyroflow to be installed somewhere in the system for OFX plugin to work?

Lastly, could you also provide instruction to compile from source?

**Comment by AdrianEddy** [comment]
please test latest dev build: https://gyroflow.xyz/devbuild/

**Comment by AdrianEddy** [comment]
Fixed in latest dev build https://gyroflow.xyz/devbuild/
