### ISSUE TITLE
Davinci 18.5 & 18.6 Plugin is not working correctly

### ISSUE THREAD

**Issue by SheepyWang** [gyroflow/gyroflow-ofx#46]
Under these two versions, the videos after the plugin stabilizes all have stripes. 
![QQ截图20230927000227](https://github.com/gyroflow/gyroflow-ofx/assets/21193219/791a2a7e-8071-4676-936f-fd640170fc84)
Additionally, in version 18.6, the plugin cannot correctly retrieve the video's path.

**Comment by AdrianEddy** [comment]
Which system?

**Comment by SheepyWang** [comment]
> Which system?

Windows 11 22H2. The picture was captured by davinci 18.5.1.

**Comment by AdrianEddy** [comment]
Which GPU are you using? Do you have CUDA selected in Resolve preferences? Did you enable local scripting in Resolve preferences? What are you timeline dimensions?
I can't reproduce this, I just installed 18.6 and everything works fine, including "Load for current file" button
I'll need more details about your case

**Comment by SheepyWang** [comment]
> Which GPU are you using? Do you have CUDA selected in Resolve preferences? Did you enable local scripting in Resolve preferences? What are you timeline dimensions? I can't reproduce this, I just installed 18.6 and everything works fine, including "Load for current file" button I'll need more details about your case
> 
> Also, you may try the latest dev build of the plugin https://nightly.link/gyroflow/gyroflow-ofx/workflows/build/main/gyroflow-ofx-windows.zip

RTX 3080.  CUDA is selected. local scripting is enable. Here this the screen shot.
![GPU](https://github.com/gyroflow/gyroflow-ofx/assets/21193219/2425a4e2-0675-4472-9b1f-9a1357eafd8c)
![Script](https://github.com/gyroflow/gyroflow-ofx/assets/21193219/a410638f-7dd5-48a4-9675-71e275ae5518)
![timeline](https://github.com/gyroflow/gyroflow-ofx/assets/21193219/d2734b44-f327-4692-a1a3-efea8aae7860)
![video](https://github.com/gyroflow/gyroflow-ofx/assets/21193219/3f304964-bb13-4e58-bf4c-d216bcd0a314)

've now fallen back to 18.5.1. "Load for current file" works fine. I'll try reinstalling 18.6 again. Wait a minute.

**Comment by AdrianEddy** [comment]
it's weird, do you have latest driver from nvidia.com installed?
Does anything change if you change the timeline dimensions to 4k for example or something else?
Can you maybe upload the file, so I can check if it behaves the same on my computer?

**Comment by SheepyWang** [comment]
Changing the timeline to 4K didn't work. 
Here is the video link. [https://drive.google.com/file/d/14wHsed10MkgRCAgXG22ru6DEov0Z9yor/view?usp=sharing](url)

**Comment by AdrianEddy** [comment]
Hmm, works fine for me, I have RTX 3080 Ti
Maybe update that driver?

![image](https://github.com/gyroflow/gyroflow-ofx/assets/3849067/3176fc94-e706-4be4-ba7a-525383baa9ed)

**Comment by SheepyWang** [comment]
> Hmm, works fine for me, I have RTX 3080 Ti Maybe update that driver?
> 
> ![image](https://user-images.githubusercontent.com/3849067/270756298-3176fc94-e706-4be4-ba7a-525383baa9ed.png)

It works！ Thank you so much.
