### ISSUE TITLE
Gyroflow OFX plugin Memory leak

### ISSUE THREAD

**Issue by mailsone** [gyroflow/gyroflow-ofx#49]
It looks like there is memory leak inside fusion page.

I am working on 2019 Intel Mac (MacOS Sonoma) and Davinci Resolve 18.6. Not sure if the problem was present before MacOS Sonoma, as I just start using the gyroflow recently.

**Comment by AdrianEddy** [comment]
Please test latest dev build https://gyroflow.xyz/devbuild/
