### ISSUE TITLE
Jittery footage in DaVinci Resolve, smooth in standalone app

### ISSUE THREAD

**Issue by video-newb** [gyroflow/gyroflow-ofx#54]
DaVinci Resolve 18.6.2
Gyroflow OFX v1.3.0
M1 Pro, macOS 14.0
Sony ZV-E1 on 1.02 firmware
59.94 fps H.265 4:2:2 (In-body stabilization disabled)

I've used the plugin a few months ago with no issues, not sure what went wrong this time around. I updated everything to the latest versions but the issues still remain. There's also a second in the beginning that is skipped. Anyone else run into these same issues or something similar?

Also, with the latest versions installed, clicking "Open in Gyroflow" returns the error "Failed to load the selected file, it may be unsupported or invalid." Did not have this issue before updating. Again, opening the file from Gyroflow works fine.

**Comment by AdrianEddy** [comment]
Most likely timeline fps mismatch? Your timeline fps needs to be the same as video fps

Is your Gyroflow installed from .dmg or app store?

**Comment by video-newb** [comment]
Wow, thank you so much for the quick response. That was exactly it! My DaVinci timeline is 60fps instead of 59.94fps. Importing the same clip to a proper 59.94fps timeline have fixed the issue. I had seen the warning but thought it was not active because the text was grayed out so I ignored it. 

And I installed the previous version of Gyroflow from .dmg. The current version 1.5.4 was installed through the App store. 

Thanks again!

**Comment by AdrianEddy** [comment]
You can install v1.5.4 from .dmg from here https://github.com/gyroflow/gyroflow/releases/tag/v1.5.4
Apparently Apple's App Sandbox (required for app store apps) doesn't play well with these interoperability functions from the plugin, so it's better to use the .dmg version if you're also using the plugin. Gyroflow will always be released as .dmg as well in the future

**Comment by video-newb** [comment]
I just reinstalled from .dmg and the error message from "Open in Gyroflow" has also gone away. Everything works as expected. Thank you!
