### ISSUE TITLE
Slow playback in windows Davinci Resolve Studio

### ISSUE THREAD

**Issue by carbendi** [gyroflow/gyroflow-ofx#6]
I am having slow playback issue in windows with Davinci Resolve Studio after applying the plugin in fusion.

Playback speed is around 1 frame per minute. 

File: 
Gopro8 2.7k 4:3 50fps

Specs of the PC;
Rtx 3070
64GB Ram
AMD Ryzen 9 5950X 16-Core Processor 
Windows 10
Files are being read from SSD

**Comment by rootbsd** [comment]
I can confirm the same performance issue. More or less 1 frame per minute.

**Comment by carbendi** [comment]
This slow playback was with the previous version. The new version is working great. Maybe only thing missing is the dynamic crop on OFX. But still it is great to be able to stabilise the raw file. Thank you for the work.

**Comment by ilya-epifanov** [comment]
closing this for now
