### ISSUE TITLE
Sync issues when using cut page in Resolve 18.6

### ISSUE THREAD

**Issue by dizzybro** [gyroflow/gyroflow-ofx#60]
I've notice that when I use the cut page in resolve to create clip for my timeline and then apply stabilization to my clips through the plugin, I get jitters that appear to be from lack of sync. This does only happen when using 60p footage on a 30p timeline. If i drop the same 60p clips on my 30p timeline using the edit page, and do my trimming there, the stabilization can be applied without issue. My camera is the Sony FX30.

**Comment by AdrianEddy** [comment]
This should be fixed in the latest dev build of the new plugin https://gyroflow.xyz/devbuild/
