### ISSUE TITLE
Fisheye stabilization missing from fussion

### ISSUE THREAD

**Issue by michael-blue2** [gyroflow/gyroflow-ofx#7]
At first the fisheye correction was in the fusion tab, When i went back to davinci to stabilize a 2nd clip it just gone missing. I can still find it in the color tab but I cannot find in the fussion for a reason. Using 17.1 on windows machine

**Comment by Pirch0** [comment]
Unfortunately fisheye stabilisation node is not visible in Davinci Resolve Fusion 17.1.4 Build 4 OSX Big Sur (Bug Sure). I have copied it to the library, plugins, ofx folder, next to the other .bundle files. It looked like a very helpful tool!

**Comment by ilya-epifanov** [comment]
Please make sure it's enabled in Preferences.

![image](https://user-images.githubusercontent.com/92526/152996735-72bbf36b-4b73-4e16-bb64-2f43c2171688.png)
