### ISSUE TITLE
OFX Plugin not Showing up in Resolve 17

### ISSUE THREAD

**Issue by noahwaldner** [gyroflow/gyroflow-ofx#9]
OFX Plugin not Showing up in Resolve 17

Neither Gyroflow nor Fisheye Stabilizer show up in the list

**Comment by ilya-epifanov** [comment]
Please make sure it's enabled in Preferences.

![image](https://user-images.githubusercontent.com/92526/152996735-72bbf36b-4b73-4e16-bb64-2f43c2171688.png)
